trigger:
 branches:
   include:
     - master
 paths:
   include:
     - Aqua.WebApp

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: Aqua.WebApp